# Generated by Django 5.0.10 on 2026-04-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
